### PR TITLE
v2.3.2

### PR DESCRIPTION
**Pull request by martin-raden**

### CODE REVIEW

**Comment by martin-raden** [comment]
@simonbray man thanks again for the gh action integration of the tests!

**Comment by martin-raden** [comment]
@bgruening how do I get rid of the travis-ci integration? there is nothing left in the settings. is this within the travis-ci UI? and if so: who can edit?

**Comment by bgruening** [comment]
Where do you see travis?

**Comment by martin-raden** [comment]
within IntaRNA master PRs

**Comment by bgruening** [comment]
Mh, I don't see them. I only see GitHub actions.

**Pull request merged**
